version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_URL: "mongodb://mongodb:27017/parking"